spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/aicodereview?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Anwar@12345$}
  jpa:
    show-sql: true
  flyway:
    enabled: true
